#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
#  Evernode Cluster Manager — Setup Script
#  Run once to configure your environment.
#  Usage: bash setup.sh
# ══════════════════════════════════════════════════════════════

set -e

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║       Evernode Cluster Manager — Setup              ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""

# ── Detect script location ────────────────────────────────────
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Check dependencies ────────────────────────────────────────
echo "Checking dependencies..."
if ! command -v node &>/dev/null; then
    echo "  ✗ Node.js not found. Install Node.js v20+ and try again."
    exit 1
fi
NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
if [ "$NODE_VERSION" -lt 20 ]; then
    echo "  ✗ Node.js v20+ required. Current: $(node -v)"
    exit 1
fi
echo "  ✓ Node.js $(node -v)"

if ! command -v evdevkit &>/dev/null; then
    echo "  ✗ evdevkit not found. Installing..."
    npm i evdevkit -g
fi
echo "  ✓ evdevkit installed"
echo ""

# ── Project directory ─────────────────────────────────────────
echo "── Project Setup ─────────────────────────────────────────"
read -rp "  Project directory name (default: evernode_client): " DIR_NAME
DIR_NAME="${DIR_NAME:-evernode_client}"

if [ "$(id -u)" -eq 0 ]; then
    read -rp "  Install under which user's home? (default: $(logname 2>/dev/null || echo $SUDO_USER)): " TARGET_USER
    TARGET_USER="${TARGET_USER:-$(logname 2>/dev/null || echo $SUDO_USER)}"
    BASE_HOME="/home/$TARGET_USER"
else
    BASE_HOME="$HOME"
    TARGET_USER="$(whoami)"
fi

PROJECT_DIR="$BASE_HOME/$DIR_NAME"
echo ""
echo "  Project will be created at: $PROJECT_DIR"
read -rp "  Confirm? (yes/y): " CONFIRM
if [[ "$CONFIRM" != "yes" && "$CONFIRM" != "y" ]]; then
    echo "  Cancelled."
    exit 0
fi

mkdir -p "$PROJECT_DIR"/{contract,client,config,host}
echo "  ✓ Directory created: $PROJECT_DIR"
echo ""

# ── Generate user keys ────────────────────────────────────────
echo "── Key Generation ────────────────────────────────────────"
echo "  Do you have existing HotPocket user keys?"
read -rp "  (yes/y to enter them, anything else to generate new): " HAS_KEYS

if [[ "$HAS_KEYS" == "yes" || "$HAS_KEYS" == "y" ]]; then
    read -rp "  EV_USER_PRIVATE_KEY: " EV_USER_PRIVATE_KEY
    read -rp "  EV_USER_PUBLIC_KEY : " EV_USER_PUBLIC_KEY
else
    echo "  Generating new key pair via evdevkit keygen..."
    KEYGEN_OUTPUT=$(evdevkit keygen 2>&1)
    echo "$KEYGEN_OUTPUT"
    EV_USER_PRIVATE_KEY=$(echo "$KEYGEN_OUTPUT" | grep -i private | grep -o 'ed[a-f0-9]\+' | head -1)
    EV_USER_PUBLIC_KEY=$(echo "$KEYGEN_OUTPUT" | grep -i public | grep -o 'ed[a-f0-9]\+' | head -1)
    if [ -z "$EV_USER_PRIVATE_KEY" ]; then
        echo "  ✗ Key generation failed. Run 'evdevkit keygen' manually and re-run setup."
        exit 1
    fi
    echo "  ✓ Keys generated."
fi
echo ""

# ── XRPL Tenant credentials ───────────────────────────────────
echo "── XRPL Tenant Credentials ───────────────────────────────"
echo "  Your XRPL wallet pays for instance leases."
read -rp "  EV_TENANT_SECRET : " EV_TENANT_SECRET
read -rp "  EV_TENANT_ADDRESS: " EV_TENANT_ADDRESS
echo ""

# ── HotPocket settings ────────────────────────────────────────
echo "── HotPocket Settings ────────────────────────────────────"
read -rp "  Consensus round time ms (default 5000)   : " HP_ROUNDTIME
HP_ROUNDTIME="${HP_ROUNDTIME:-5000}"
read -rp "  Consensus threshold % (default 66)       : " HP_THRESHOLD
HP_THRESHOLD="${HP_THRESHOLD:-66}"
read -rp "  Log level err/inf/dbg (default dbg)      : " HP_LOG_LEVEL
HP_LOG_LEVEL="${HP_LOG_LEVEL:-dbg}"
read -rp "  Peer discovery true/false (default false) : " HP_PEER_DISCOVERY
HP_PEER_DISCOVERY="${HP_PEER_DISCOVERY:-false}"
echo ""

# ── Contract settings ─────────────────────────────────────────
echo "── Contract Settings ─────────────────────────────────────"
read -rp "  Starting contract version (default v1.0.0): " CONTRACT_VERSION
CONTRACT_VERSION="${CONTRACT_VERSION:-v1.0.0}"
read -rp "  Default node count (default 3)            : " DEFAULT_NODE_COUNT
DEFAULT_NODE_COUNT="${DEFAULT_NODE_COUNT:-3}"
read -rp "  Default life moments (default 3)          : " DEFAULT_MOMENTS
DEFAULT_MOMENTS="${DEFAULT_MOMENTS:-3}"
echo ""

# ── Write .env ────────────────────────────────────────────────
cat > "$PROJECT_DIR/config/.env" << EOF
# Evernode Cluster Manager — Configuration
# Generated by setup.sh on $(date)

# ── Project ───────────────────────────────────────────
PROJECT_DIR=$PROJECT_DIR

# ── XRPL Tenant Identity ──────────────────────────────
EV_TENANT_SECRET=$EV_TENANT_SECRET
EV_TENANT_ADDRESS=$EV_TENANT_ADDRESS
EV_USER_PRIVATE_KEY=$EV_USER_PRIVATE_KEY
EV_USER_PUBLIC_KEY=$EV_USER_PUBLIC_KEY

# ── Cluster Defaults ──────────────────────────────────
DEFAULT_NODE_COUNT=$DEFAULT_NODE_COUNT
DEFAULT_MOMENTS=$DEFAULT_MOMENTS

# ── HotPocket Settings ────────────────────────────────
HP_ROUNDTIME=$HP_ROUNDTIME
HP_THRESHOLD=$HP_THRESHOLD
HP_LOG_LEVEL=$HP_LOG_LEVEL
HP_PEER_DISCOVERY=$HP_PEER_DISCOVERY

# ── Contract ──────────────────────────────────────────
CONTRACT_VERSION=$CONTRACT_VERSION
EOF
chmod 600 "$PROJECT_DIR/config/.env"
echo "  ✓ Config written to $PROJECT_DIR/config/.env"

# ── Write hp-init.cfg ─────────────────────────────────────────
cat > "$PROJECT_DIR/config/hp-init.cfg" << EOF
{
  "contract": {
    "consensus": {
      "roundtime": $HP_ROUNDTIME,
      "threshold": $HP_THRESHOLD
    }
  },
  "mesh": {
    "peer_discovery": {
      "enabled": $HP_PEER_DISCOVERY
    }
  },
  "log": {
    "log_level": "$HP_LOG_LEVEL"
  }
}
EOF
echo "  ✓ hp-init.cfg written"

# ── Write hp.cfg.override ─────────────────────────────────────
cat > "$PROJECT_DIR/config/hp.cfg.override" << EOF
{
  "contract": {
    "bin_path": "/usr/bin/node",
    "bin_args": "index.js",
    "consensus": {
      "roundtime": $HP_ROUNDTIME,
      "threshold": $HP_THRESHOLD
    }
  }
}
EOF
echo "  ✓ hp.cfg.override written"

# ── Copy files from repo ──────────────────────────────────────
echo ""
echo "  Copying project files..."
cp "$REPO_DIR/contract/index.js"          "$PROJECT_DIR/contract/index.js"
cp "$REPO_DIR/contract/package.json"      "$PROJECT_DIR/contract/package.json"
cp "$PROJECT_DIR/config/hp.cfg.override"  "$PROJECT_DIR/contract/hp.cfg.override"
sed -i "s/const CONTRACT_VERSION       = '[^']*'/const CONTRACT_VERSION       = '$CONTRACT_VERSION'/" "$PROJECT_DIR/contract/index.js"
echo "  ✓ Contract files copied (version: $CONTRACT_VERSION)"

cp "$REPO_DIR/client/deploy.sh"           "$PROJECT_DIR/client/deploy.sh"
cp "$REPO_DIR/client/cluster-manager.js"  "$PROJECT_DIR/client/cluster-manager.js"
cp "$REPO_DIR/client/package.json"        "$PROJECT_DIR/client/package.json"
chmod +x "$PROJECT_DIR/client/deploy.sh"
echo "  ✓ Client files copied"

cp "$REPO_DIR/host/post-deploy-patch.sh"  "$PROJECT_DIR/host/post-deploy-patch.sh"
chmod +x "$PROJECT_DIR/host/post-deploy-patch.sh"
echo "  ✓ Host files copied"

# ── Install dependencies ──────────────────────────────────────
echo ""
echo "  Installing contract dependencies..."
npm install --prefix "$PROJECT_DIR/contract" --silent
echo "  ✓ Done"
echo "  Installing client dependencies..."
npm install --prefix "$PROJECT_DIR/client" --silent
echo "  ✓ Done"

chown -R "$TARGET_USER":"$TARGET_USER" "$PROJECT_DIR" 2>/dev/null || true

# ── Done ──────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║              Setup Complete!                        ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  Project : $PROJECT_DIR"
echo "  Config  : $PROJECT_DIR/config/.env"
echo ""
echo "  Next steps:"
echo ""
echo "  1. Deploy a cluster:"
echo "     bash $PROJECT_DIR/client/deploy.sh"
echo ""
echo "  2. Manage the cluster:"
echo "     node $PROJECT_DIR/client/cluster-manager.js <ip> <port> <contract_id>"
echo ""
